spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    user:
      name: user
      password: 12345
    oauth2:
      resourceserver:
        jwt:
          authorities-claim-name: authorities # The claim name that stores the authorities in the JWT token (the custom claim name that the JwtAuthenticationConverter should inspect).
          authority-prefix: "" # The prefix that will be added to the authorities in the JWT token. The default one is "SCOPE_". In this project, you need to change it to empty, that is, no prefix!
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true

api:
  endpoint:
    base-url: /api/v1

